sudo: required
services:
  - docker
script:
  - docker build . -t voikkospell
before_deploy:
  - mkdir voikkospell
  - docker run -v $PWD/voikkospell:/out voikkospell
  - tar zcf voikkospell.tar.gz voikkospell
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: voikkospell.tar.gz
  skip_cleanup: true
  on:
    tags: true
